30 result box integration
xgarciagSopra/squad1_wordle_front pull request #19
Opened 2023-04-27 11:01 UTC by xgarciagSopra

CSS casillas y corrección de css de selección de casilla

2023-04-27 12:10 UTC, ddiezgsop requested changes

2023-04-27 12:10 UTC, ddiezgsop commented on src/app/app.component.spec.ts
> +xdescribe('AppComponent', () => {
```suggestion
describe('AppComponent', () => {
```

xdescribe?

2023-04-27 12:10 UTC, ddiezgsop commented on src/app/components/game-center/game-center.component.spec.ts
> +  // });
```suggestion
   it('should check', () => {
     expect(component).toBeTruthy();
   });
```

Do not upload commented code

2023-04-27 12:10 UTC, ddiezgsop commented on src/app/components/result-box/result-box.component.scss
> +}
Use a class in `<p>` to give it `color: white` and change the background-color when u need. Notice that u are repeating code 3 times

2023-04-27 12:10 UTC, ddiezgsop commented on src/app/components/result-box/result-box.component.ts
> +  @Input() keyBoxStyle: string = '';
```suggestion
  @Input() keyBoxStyle = '';
```

2023-04-27 12:10 UTC, ddiezgsop commented on src/app/components/result-box/result-box.component.ts
> +      'border-primary': this.selectedBox === index,
```suggestion
      'selectedSquare': this.selectedBox === index,
```

Use a more clarifing variable

2023-04-27 12:10 UTC, ddiezgsop commented on src/app/components/result-box/result-box.component.ts
> +      '': !this.firstRound,
```suggestion
```

Don't use this case, if u don't give any styles, don't give any condition

2023-04-27 12:10 UTC, ddiezgsop commented on src/app/services/guess-word.service.spec.ts
> +      providers: [HttpClient, HttpHandler],
```suggestion
      imports: [HttpClientTestingModule],
```

When u are testing the http service, u need to import the HttpTestingModule in imports

2023-04-27 14:21 UTC, xgarciagSopra commented on src/app/app.component.spec.ts
> +xdescribe('AppComponent', () => {
Lo pusiste tu, cuando me tocaste el spec, no he tocado nada

2023-04-27 14:30 UTC, xgarciagSopra commented on src/app/components/result-box/result-box.component.ts
> +      'border-primary': this.selectedBox === index,
es de boostrap, si pongo el selectedSquare no me deja poner un borde con color de normal dentro de css

2023-04-27 14:33 UTC, ddiezgsop commented on src/app/app.component.spec.ts
> +xdescribe('AppComponent', () => {
Leave it, xdescribe and fdescribe shouldn't be uploaded

2023-04-28 07:54 UTC, ddiezgsop commented on src/app/components/result-box/result-box.component.scss
> +}
```suggestion
.baseSquare {
  color: white;
}
```

2023-04-28 08:45 UTC, ddiezgsop approved these changes

2023-04-28 08:47 UTC, merged